# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redoc.ly/docs/cli/ for more information.
_schema.yaml:
  no-empty-servers:
    - '#/openapi'
  no-identical-paths:
    - '#/paths/~1api~1groups~1{group_id}~1roles~1{role_id}'
    - '#/paths/~1api~1groups~1{group_id}~1user~1{user_id}'
    - '#/paths/~1api~1groups~1{group_id}~1users~1{user_id}'
  no-ambiguous-paths:
    - '#/paths/~1api~1groups~1{group_id}~1roles~1{role_id}'
    - '#/paths/~1api~1groups~1{group_id}~1user~1{user_id}'
    - '#/paths/~1api~1groups~1{group_id}~1users~1{user_id}'
    - '#/paths/~1api~1histories~1{history_id}~1contents~1archive~1{id}'
    - >-
      #/paths/~1api~1histories~1{history_id}~1contents~1{dataset_id}~1permissions
    - >-
      #/paths/~1api~1histories~1{history_id}~1contents~1{history_content_id}~1display
    - >-
      #/paths/~1api~1histories~1{history_id}~1contents~1{history_content_id}~1extra_files
    - >-
      #/paths/~1api~1histories~1{history_id}~1contents~1{history_content_id}~1metadata_file
    - '#/paths/~1api~1histories~1{history_id}~1contents~1{id}~1validate'
    - '#/paths/~1api~1histories~1{history_id}~1contents~1{type}s~1{id}'
  path-parameters-defined:
    - >-
      #/paths/~1api~1histories~1{history_id}~1contents~1archive~1{id}/get/parameters
  operation-4xx-response:
    - '#/paths/~1api~1datatypes~1converters/get/responses'
    - '#/paths/~1api~1datatypes~1edam_data/get/responses'
    - '#/paths/~1api~1datatypes~1edam_data~1detailed/get/responses'
    - '#/paths/~1api~1datatypes~1edam_formats/get/responses'
    - '#/paths/~1api~1datatypes~1edam_formats~1detailed/get/responses'
    - '#/paths/~1api~1datatypes~1mapping/get/responses'
    - '#/paths/~1api~1datatypes~1sniffers/get/responses'
    - '#/paths/~1api~1licenses/get/responses'
    - '#/paths/~1api~1tours/get/responses'
    - '#/paths/~1api~1version/get/responses'
    - '#/paths/~1ga4gh~1drs~1v1~1service-info/get/responses'
  security-defined:
    - '#/paths/~1api~1datatypes/get'
    - '#/paths/~1api~1datatypes~1converters/get'
    - '#/paths/~1api~1datatypes~1edam_data/get'
    - '#/paths/~1api~1datatypes~1edam_data~1detailed/get'
    - '#/paths/~1api~1datatypes~1edam_formats/get'
    - '#/paths/~1api~1datatypes~1edam_formats~1detailed/get'
    - '#/paths/~1api~1datatypes~1mapping/get'
    - '#/paths/~1api~1datatypes~1sniffers/get'
    - '#/paths/~1api~1datatypes~1types_and_mapping/get'
    - '#/paths/~1api~1genomes~1{id}~1indexes/get'
    - '#/paths/~1api~1licenses/get'
    - '#/paths/~1api~1licenses~1{id}/get'
    - '#/paths/~1api~1short_term_storage~1{storage_request_id}/get'
    - '#/paths/~1api~1short_term_storage~1{storage_request_id}~1ready/get'
    - '#/paths/~1api~1tasks~1{task_id}~1state/get'
    - '#/paths/~1api~1tool_shed_repositories/get'
    - '#/paths/~1api~1tool_shed_repositories~1{id}/get'
    - '#/paths/~1api~1tours/get'
    - '#/paths/~1api~1tours~1{tour_id}/get'
    - '#/paths/~1api~1version/get'
    - '#/paths/~1ga4gh~1drs~1v1~1service-info/get'
