tool_form_base:
  title: Tool Form
  file_path: tools/tool_form_base.md
collection_builder:
  title: Collection Builder
  file_path: collections/collection_builder.md
selector_modal_switch:
  title: History Selector
  file_path: histories/selector_modal_switch.md
selector_modal_multiview:
  title: History Selector
  file_path: histories/selector_modal_multiview.md
